import argparse
from pathlib import Path
import cv2
import numpy as np
from PIL import Image
from tqdm import tqdm

import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision.transforms.functional import to_tensor

from utils.metrics import psnr, ssim
from data.patchpair import SelectivePatchPairSampler, SelectivePatchPairConfig
from models.gs2tnet import GS2TNet
from models.mstanet import MSTANet

class HRFolderDataset(Dataset):
    """
    Expects a folder of HR images. LR is generated by bicubic downsampling.
    For training, returns patch pairs via selective patch-pair sampling. :contentReference[oaicite:22]{index=22}
    """
    def __init__(self, hr_dir: str, scale: int, patch_hr: int = 96, use_selective=True):
        self.paths = sorted([p for p in Path(hr_dir).glob("*") if p.suffix.lower() in [".png",".jpg",".jpeg",".bmp"]])
        self.scale = scale
        self.use_selective = use_selective
        self.sampler = SelectivePatchPairSampler(SelectivePatchPairConfig(scale=scale, patch_hr=patch_hr))

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, idx):
        img = Image.open(self.paths[idx]).convert("RGB")
        hr = to_tensor(img)  # (C,H,W) in [0,1]

        if self.use_selective:
            lr_patch, hr_patch = self.sampler.sample(hr)
        else:
            # fallback: random patch without filtering
            C, H, W = hr.shape
            ph = self.sampler.cfg.patch_hr
            s = self.scale
            pl = ph // s
            y = np.random.randint(0, H - ph)
            x = np.random.randint(0, W - ph)
            hr_patch = hr[:, y:y+ph, x:x+ph]
            lr = F.interpolate(hr.unsqueeze(0), scale_factor=1.0/s, mode="bicubic", align_corners=False).squeeze(0)
            lr_patch = lr[:, y//s:y//s+pl, x//s:x//s+pl]

        return lr_patch, hr_patch

def pseudo_text_mask(hr: torch.Tensor) -> torch.Tensor:
    """
    Optional pseudo supervision for attention losses when real text masks are not available.
    Produces an edge-like mask from HR using Sobel magnitude + normalization.
    """
    # hr: (B,C,H,W)
    gray = hr.mean(dim=1, keepdim=True)
    # simple sobel
    kx = torch.tensor([[-1,0,1],[-2,0,2],[-1,0,1]], device=hr.device, dtype=hr.dtype).view(1,1,3,3)
    ky = torch.tensor([[-1,-2,-1],[0,0,0],[1,2,1]], device=hr.device, dtype=hr.dtype).view(1,1,3,3)
    gx = F.conv2d(gray, kx, padding=1)
    gy = F.conv2d(gray, ky, padding=1)
    mag = torch.sqrt(gx*gx + gy*gy + 1e-8)
    mag = mag / (mag.amax(dim=(2,3), keepdim=True) + 1e-8)
    return mag  # (B,1,H,W)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hr_dir", type=str, required=True)
    ap.add_argument("--model", type=str, choices=["gs2tnet","mstanet"], default="mstanet")
    ap.add_argument("--scale", type=int, default=3)
    ap.add_argument("--epochs", type=int, default=100)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--lr", type=float, default=1e-4)
    ap.add_argument("--patch_hr", type=int, default=96)
    ap.add_argument("--save", type=str, default="checkpoints")
    ap.add_argument("--use_attention_loss", action="store_true")
    args = ap.parse_args()

    device = "cuda" if torch.cuda.is_available() else "cpu"
    ds = HRFolderDataset(args.hr_dir, scale=args.scale, patch_hr=args.patch_hr, use_selective=True)
    dl = DataLoader(ds, batch_size=args.batch, shuffle=True, num_workers=2, pin_memory=True)

    if args.model == "gs2tnet":
        net = GS2TNet(scale=args.scale).to(device)
    else:
        net = MSTANet(scale=args.scale, num_oia=2, use_blstm=True).to(device)

    opt = torch.optim.Adam(net.parameters(), lr=args.lr, betas=(0.9, 0.999))

    Path(args.save).mkdir(parents=True, exist_ok=True)

    for ep in range(1, args.epochs + 1):
        net.train()
        pbar = tqdm(dl, desc=f"Epoch {ep}/{args.epochs}")
        loss_sum = 0.0

        for lr_patch, hr_patch in pbar:
            lr_patch = lr_patch.to(device)
            hr_patch = hr_patch.to(device)

            if args.model == "gs2tnet":
                sr = net(lr_patch)
                loss = F.l1_loss(sr, hr_patch)  # your GS2TNet uses L1 in the PDF :contentReference[oaicite:23]{index=23}
            else:
                sr, aux = net(lr_patch)
                loss = F.mse_loss(sr, hr_patch)  # MSTANet primary MSE in PDF :contentReference[oaicite:24]{index=24}

                if args.use_attention_loss:
                    mask = pseudo_text_mask(hr_patch)
                    # encourage attention maps to align with text/edge regions
                    loss_o = F.l1_loss(aux["attn_o"], mask)
                    loss_s = F.l1_loss(aux["attn_s"], mask)
                    loss = loss + 0.5 * loss_o + 1.0 * loss_s  # (λo, λs) example; tune

            opt.zero_grad(set_to_none=True)
            loss.backward()
            opt.step()

            loss_sum += loss.item()
            pbar.set_postfix(loss=loss.item())

        # quick train metrics on last batch (lightweight)
        with torch.no_grad():
            if args.model == "gs2tnet":
                sr_eval = sr
            else:
                sr_eval = sr
            p = psnr(sr_eval, hr_patch).mean().item()
            s = ssim(sr_eval, hr_patch).mean().item()

        ckpt = Path(args.save) / f"{args.model}_x{args.scale}_ep{ep}.pt"
        torch.save({"epoch": ep, "state_dict": net.state_dict()}, ckpt)

        print(f"[Epoch {ep}] avg_loss={loss_sum/len(dl):.6f} PSNR={p:.3f} SSIM={s:.4f} saved={ckpt}")

if __name__ == "__main__":
    main()
